// This file is generated from mgl32/matrix.go; DO NOT EDIT

// Copyright 2014 The go-gl/mathgl Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// This file is generated by codegen.go; DO NOT EDIT
// Edit matrix.tmpl and run "go generate" to make changes.

package mgl64

type Mat2 [2 * 2]float64
type Mat2x3 [2 * 3]float64
type Mat2x4 [2 * 4]float64
type Mat3x2 [3 * 2]float64
type Mat3 [3 * 3]float64
type Mat3x4 [3 * 4]float64
type Mat4x2 [4 * 2]float64
type Mat4x3 [4 * 3]float64
type Mat4 [4 * 4]float64

func (m Mat2) Mat3() Mat3 { _ = "STUB: not implemented"; return *new(Mat3) }

func (m Mat2) Mat4() Mat4 { _ = "STUB: not implemented"; return *new(Mat4) }

func (m Mat3) Mat2() Mat2 { _ = "STUB: not implemented"; return *new(Mat2) }

func (m Mat3) Mat4() Mat4 { _ = "STUB: not implemented"; return *new(Mat4) }

func (m Mat4) Mat2() Mat2 { _ = "STUB: not implemented"; return *new(Mat2) }

func (m Mat4) Mat3() Mat3 { _ = "STUB: not implemented"; return *new(Mat3) }

// SetCol sets a Column within the Matrix, so it mutates the calling matrix.
func (m *Mat2) SetCol(col int, v Vec2) { _ = "STUB: not implemented"; return }

// SetRow sets a Row within the Matrix, so it mutates the calling matrix.
func (m *Mat2) SetRow(row int, v Vec2) { _ = "STUB: not implemented"; return }

// Diag is a basic operation on a square matrix that simply
// returns main diagonal (meaning all elements such that row==col).
func (m Mat2) Diag() Vec2 {
	_ = "STUB: not implemented"
	return *

	// Ident2 returns the 2x2 identity matrix.
	// The identity matrix is a square matrix with the value 1 on its
	// diagonals. The characteristic property of the identity matrix is that
	// any matrix multiplied by it is itself. (MI = M; IN = N)
	new(Vec2)
}

func Ident2() Mat2 {
	_ = "STUB: not implemented"
	return *

	// Diag2 creates a diagonal matrix from the entries of the input vector.
	// That is, for each pointer for row==col, vector[row] is the entry. Otherwise it's 0.
	//
	// Another way to think about it is that the identity is this function where the every vector element is 1.
	new(Mat2)
}

func Diag2(v Vec2) Mat2 { _ = "STUB: not implemented"; return *new(Mat2) }

// Mat2FromRows builds a new matrix from row vectors.
// The resulting matrix will still be in column major order, but this can be
// good for hand-building matrices.

func Mat2FromRows(row0, row1 Vec2) Mat2 { _ = "STUB: not implemented"; return *new(Mat2) }

// Mat2FromCols builds a new matrix from column vectors.
func Mat2FromCols(col0, col1 Vec2) Mat2 { _ = "STUB: not implemented"; return *new(Mat2) }

// Add performs an element-wise addition of two matrices, this is
// equivalent to iterating over every element of m1 and adding the corresponding value of m2.
func (m1 Mat2) Add(m2 Mat2) Mat2 { _ = "STUB: not implemented"; return *new(Mat2) }

// Sub performs an element-wise subtraction of two matrices, this is
// equivalent to iterating over every element of m1 and subtracting the corresponding value of m2.
func (m1 Mat2) Sub(m2 Mat2) Mat2 { _ = "STUB: not implemented"; return *new(Mat2) }

// Mul performs a scalar multiplcation of the matrix. This is equivalent to iterating
// over every element of the matrix and multiply it by c.
func (m1 Mat2) Mul(c float64) Mat2 { _ = "STUB: not implemented"; return *new(Mat2) }

// Mul2x1 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat2) Mul2x1(m2 Vec2) Vec2 { _ = "STUB: not implemented"; return *new(Vec2) }

// Mul2 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat2) Mul2(m2 Mat2) Mat2 { _ = "STUB: not implemented"; return *new(Mat2) }

// Mul2x3 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat2) Mul2x3(m2 Mat2x3) Mat2x3 { _ = "STUB: not implemented"; return *new(Mat2x3) }

// Mul2x4 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat2) Mul2x4(m2 Mat2x4) Mat2x4 { _ = "STUB: not implemented"; return *new(Mat2x4) }

// Transpose produces the transpose of this matrix. For any MxN matrix
// the transpose is an NxM matrix with the rows swapped with the columns. For instance
// the transpose of the Mat3x2 is a Mat2x3 like so:
//
//	[[a b]]    [[a c e]]
//	[[c d]] =  [[b d f]]
//	[[e f]]
func (m1 Mat2) Transpose() Mat2 { _ = "STUB: not implemented"; return *new(Mat2) }

// Det returns the determinant of a matrix. It is a measure of a square matrix's
// singularity and invertability, among other things. In this library, the
// determinant is hard coded based on pre-computed cofactor expansion, and uses
// no loops. Of course, the addition and multiplication must still be done.
func (m Mat2) Det() float64 { _ = "STUB: not implemented"; return 0 }

// Inv computes the inverse of a square matrix. An inverse is a square matrix such that when multiplied by the
// original, yields the identity.
//
// M_inv * M = M * M_inv = I
//
// In this library, the math is precomputed, and uses no loops, though the multiplications, additions, determinant calculation, and scaling
// are still done. This can still be (relatively) expensive for a 4x4.
//
// This function checks the determinant to see if the matrix is invertible.
// If the determinant is 0.0, this function returns the zero matrix. However, due to floating point errors, it is
// entirely plausible to get a false positive or negative.
// In the future, an alternate function may be written which takes in a pre-computed determinant.
func (m Mat2) Inv() Mat2 { _ = "STUB: not implemented"; return *new(Mat2) }

// ApproxEqual performs an element-wise approximate equality test between two matrices,
// as if FloatEqual had been used.
func (m1 Mat2) ApproxEqual(m2 Mat2) bool { _ = "STUB: not implemented"; return false }

// ApproxEqualThreshold performs an element-wise approximate equality test between two matrices
// with a given epsilon threshold, as if FloatEqualThreshold had been used.
func (m1 Mat2) ApproxEqualThreshold(m2 Mat2, threshold float64) bool {
	_ = "STUB: not implemented"
	return false
}

// ApproxFuncEqual performs an element-wise approximate equality test between two matrices
// with a given equality functions, intended to be used with FloatEqualFunc; although and comparison
// function may be used in practice.
func (m1 Mat2) ApproxFuncEqual(m2 Mat2, eq func(float64, float64) bool) bool {
	_ = "STUB: not implemented"
	return false
}

// NumRows returns the number of rows in this matrix
func (m Mat2) NumRows() int {
	_ = "STUB: not implemented"

	// NumCols returns the number of columns in this matrix
	return 0
}

func (m Mat2) NumCols() int {
	_ = "STUB: not implemented"

	// At returns the matrix element at the given row and column.
	// This is equivalent to mat[col * numRow + row] where numRow is constant
	// (E.G. for a Mat3x2 it's equal to 3)
	//
	// This method is garbage-in garbage-out. For instance, on a Mat4 asking for
	// At(5,0) will work just like At(1,1). Or it may panic if it's out of bounds.
	return 0
}

func (m Mat2) At(row, col int) float64 { _ = "STUB: not implemented"; return 0 }

// Set sets the corresponding matrix element at the given row and column.
// This has a pointer receiver because it mutates the matrix.
//
// This method is garbage-in garbage-out. For instance, on a Mat4 asking for
// Set(5,0,val) will work just like Set(1,1,val). Or it may panic if it's out of bounds.
func (m *Mat2) Set(row, col int, value float64) { _ = "STUB: not implemented"; return }

// Index returns the index of the given row and column, to be used with direct
// access. E.G. Index(0,0) = 0.
//
// This is a garbage-in garbage-out method. For instance, on a Mat4 asking for the index of
// (5,0) will work the same as asking for (1,1). Or it may give you a value that will cause
// a panic if you try to access the array with it if it's truly out of bounds.
func (m Mat2) Index(row, col int) int {
	_ = "STUB: not implemented"

	// Row returns a vector representing the corresponding row (starting at row 0).
	// This package makes no distinction between row and column vectors, so it
	// will be a normal VecM for a MxN matrix.
	return 0
}

func (m Mat2) Row(row int) Vec2 { _ = "STUB: not implemented"; return *new(Vec2) }

// Rows decomposes a matrix into its corresponding row vectors.
// This is equivalent to calling mat.Row for each row.
func (m Mat2) Rows() (row0, row1 Vec2) {
	_ = "STUB: not implemented"
	return *

	// Col returns a vector representing the corresponding column (starting at col 0).
	// This package makes no distinction between row and column vectors, so it
	// will be a normal VecN for a MxN matrix.
	new(Vec2), *new(Vec2)
}

func (m Mat2) Col(col int) Vec2 { _ = "STUB: not implemented"; return *new(Vec2) }

// Cols decomposes a matrix into its corresponding column vectors.
// This is equivalent to calling mat.Col for each column.
func (m Mat2) Cols() (col0, col1 Vec2) {
	_ = "STUB: not implemented"
	return *

	// Trace is a basic operation on a square matrix that simply
	// sums up all elements on the main diagonal (meaning all elements such that row==col).
	new(Vec2), *new(Vec2)
}

func (m Mat2) Trace() float64 {
	_ = "STUB: not implemented"

	// Abs returns the element-wise absolute value of this matrix
	return 0
}

func (m Mat2) Abs() Mat2 { _ = "STUB: not implemented"; return *new(Mat2) }

// Pretty prints the matrix
func (m Mat2) String() string { _ = "STUB: not implemented"; return "" }

// SetCol sets a Column within the Matrix, so it mutates the calling matrix.
func (m *Mat2x3) SetCol(col int, v Vec2) { _ = "STUB: not implemented"; return }

// SetRow sets a Row within the Matrix, so it mutates the calling matrix.
func (m *Mat2x3) SetRow(row int, v Vec3) { _ = "STUB: not implemented"; return }

// Mat2x3FromRows builds a new matrix from row vectors.
// The resulting matrix will still be in column major order, but this can be
// good for hand-building matrices.

func Mat2x3FromRows(row0, row1 Vec3) Mat2x3 { _ = "STUB: not implemented"; return *new(Mat2x3) }

// Mat2x3FromCols builds a new matrix from column vectors.
func Mat2x3FromCols(col0, col1, col2 Vec2) Mat2x3 { _ = "STUB: not implemented"; return *new(Mat2x3) }

// Add performs an element-wise addition of two matrices, this is
// equivalent to iterating over every element of m1 and adding the corresponding value of m2.
func (m1 Mat2x3) Add(m2 Mat2x3) Mat2x3 { _ = "STUB: not implemented"; return *new(Mat2x3) }

// Sub performs an element-wise subtraction of two matrices, this is
// equivalent to iterating over every element of m1 and subtracting the corresponding value of m2.
func (m1 Mat2x3) Sub(m2 Mat2x3) Mat2x3 { _ = "STUB: not implemented"; return *new(Mat2x3) }

// Mul performs a scalar multiplcation of the matrix. This is equivalent to iterating
// over every element of the matrix and multiply it by c.
func (m1 Mat2x3) Mul(c float64) Mat2x3 { _ = "STUB: not implemented"; return *new(Mat2x3) }

// Mul3x1 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat2x3) Mul3x1(m2 Vec3) Vec2 { _ = "STUB: not implemented"; return *new(Vec2) }

// Mul3x2 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat2x3) Mul3x2(m2 Mat3x2) Mat2 { _ = "STUB: not implemented"; return *new(Mat2) }

// Mul3 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat2x3) Mul3(m2 Mat3) Mat2x3 { _ = "STUB: not implemented"; return *new(Mat2x3) }

// Mul3x4 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat2x3) Mul3x4(m2 Mat3x4) Mat2x4 { _ = "STUB: not implemented"; return *new(Mat2x4) }

// Transpose produces the transpose of this matrix. For any MxN matrix
// the transpose is an NxM matrix with the rows swapped with the columns. For instance
// the transpose of the Mat3x2 is a Mat2x3 like so:
//
//	[[a b]]    [[a c e]]
//	[[c d]] =  [[b d f]]
//	[[e f]]
func (m1 Mat2x3) Transpose() Mat3x2 { _ = "STUB: not implemented"; return *new(Mat3x2) }

// ApproxEqual performs an element-wise approximate equality test between two matrices,
// as if FloatEqual had been used.
func (m1 Mat2x3) ApproxEqual(m2 Mat2x3) bool { _ = "STUB: not implemented"; return false }

// ApproxEqualThreshold performs an element-wise approximate equality test between two matrices
// with a given epsilon threshold, as if FloatEqualThreshold had been used.
func (m1 Mat2x3) ApproxEqualThreshold(m2 Mat2x3, threshold float64) bool {
	_ = "STUB: not implemented"
	return false
}

// ApproxFuncEqual performs an element-wise approximate equality test between two matrices
// with a given equality functions, intended to be used with FloatEqualFunc; although and comparison
// function may be used in practice.
func (m1 Mat2x3) ApproxFuncEqual(m2 Mat2x3, eq func(float64, float64) bool) bool {
	_ = "STUB: not implemented"
	return false
}

// NumRows returns the number of rows in this matrix
func (m Mat2x3) NumRows() int {
	_ = "STUB: not implemented"

	// NumCols returns the number of columns in this matrix
	return 0
}

func (m Mat2x3) NumCols() int {
	_ = "STUB: not implemented"

	// At returns the matrix element at the given row and column.
	// This is equivalent to mat[col * numRow + row] where numRow is constant
	// (E.G. for a Mat3x2 it's equal to 3)
	//
	// This method is garbage-in garbage-out. For instance, on a Mat4 asking for
	// At(5,0) will work just like At(1,1). Or it may panic if it's out of bounds.
	return 0
}

func (m Mat2x3) At(row, col int) float64 { _ = "STUB: not implemented"; return 0 }

// Set sets the corresponding matrix element at the given row and column.
// This has a pointer receiver because it mutates the matrix.
//
// This method is garbage-in garbage-out. For instance, on a Mat4 asking for
// Set(5,0,val) will work just like Set(1,1,val). Or it may panic if it's out of bounds.
func (m *Mat2x3) Set(row, col int, value float64) { _ = "STUB: not implemented"; return }

// Index returns the index of the given row and column, to be used with direct
// access. E.G. Index(0,0) = 0.
//
// This is a garbage-in garbage-out method. For instance, on a Mat4 asking for the index of
// (5,0) will work the same as asking for (1,1). Or it may give you a value that will cause
// a panic if you try to access the array with it if it's truly out of bounds.
func (m Mat2x3) Index(row, col int) int {
	_ = "STUB: not implemented"

	// Row returns a vector representing the corresponding row (starting at row 0).
	// This package makes no distinction between row and column vectors, so it
	// will be a normal VecM for a MxN matrix.
	return 0
}

func (m Mat2x3) Row(row int) Vec3 { _ = "STUB: not implemented"; return *new(Vec3) }

// Rows decomposes a matrix into its corresponding row vectors.
// This is equivalent to calling mat.Row for each row.
func (m Mat2x3) Rows() (row0, row1 Vec3) {
	_ = "STUB: not implemented"
	return *

	// Col returns a vector representing the corresponding column (starting at col 0).
	// This package makes no distinction between row and column vectors, so it
	// will be a normal VecN for a MxN matrix.
	new(Vec3), *new(Vec3)
}

func (m Mat2x3) Col(col int) Vec2 { _ = "STUB: not implemented"; return *new(Vec2) }

// Cols decomposes a matrix into its corresponding column vectors.
// This is equivalent to calling mat.Col for each column.
func (m Mat2x3) Cols() (col0, col1, col2 Vec2) {
	_ = "STUB: not implemented"
	return *new(Vec2), *new(Vec2), *new(Vec2)
}

// Abs returns the element-wise absolute value of this matrix
func (m Mat2x3) Abs() Mat2x3 { _ = "STUB: not implemented"; return *new(Mat2x3) }

// Pretty prints the matrix
func (m Mat2x3) String() string { _ = "STUB: not implemented"; return "" }

// SetCol sets a Column within the Matrix, so it mutates the calling matrix.
func (m *Mat2x4) SetCol(col int, v Vec2) { _ = "STUB: not implemented"; return }

// SetRow sets a Row within the Matrix, so it mutates the calling matrix.
func (m *Mat2x4) SetRow(row int, v Vec4) { _ = "STUB: not implemented"; return }

// Mat2x4FromRows builds a new matrix from row vectors.
// The resulting matrix will still be in column major order, but this can be
// good for hand-building matrices.

func Mat2x4FromRows(row0, row1 Vec4) Mat2x4 { _ = "STUB: not implemented"; return *new(Mat2x4) }

// Mat2x4FromCols builds a new matrix from column vectors.
func Mat2x4FromCols(col0, col1, col2, col3 Vec2) Mat2x4 {
	_ = "STUB: not implemented"
	return *new(Mat2x4)
}

// Add performs an element-wise addition of two matrices, this is
// equivalent to iterating over every element of m1 and adding the corresponding value of m2.
func (m1 Mat2x4) Add(m2 Mat2x4) Mat2x4 { _ = "STUB: not implemented"; return *new(Mat2x4) }

// Sub performs an element-wise subtraction of two matrices, this is
// equivalent to iterating over every element of m1 and subtracting the corresponding value of m2.
func (m1 Mat2x4) Sub(m2 Mat2x4) Mat2x4 { _ = "STUB: not implemented"; return *new(Mat2x4) }

// Mul performs a scalar multiplcation of the matrix. This is equivalent to iterating
// over every element of the matrix and multiply it by c.
func (m1 Mat2x4) Mul(c float64) Mat2x4 { _ = "STUB: not implemented"; return *new(Mat2x4) }

// Mul4x1 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat2x4) Mul4x1(m2 Vec4) Vec2 { _ = "STUB: not implemented"; return *new(Vec2) }

// Mul4x2 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat2x4) Mul4x2(m2 Mat4x2) Mat2 { _ = "STUB: not implemented"; return *new(Mat2) }

// Mul4x3 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat2x4) Mul4x3(m2 Mat4x3) Mat2x3 { _ = "STUB: not implemented"; return *new(Mat2x3) }

// Mul4 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat2x4) Mul4(m2 Mat4) Mat2x4 { _ = "STUB: not implemented"; return *new(Mat2x4) }

// Transpose produces the transpose of this matrix. For any MxN matrix
// the transpose is an NxM matrix with the rows swapped with the columns. For instance
// the transpose of the Mat3x2 is a Mat2x3 like so:
//
//	[[a b]]    [[a c e]]
//	[[c d]] =  [[b d f]]
//	[[e f]]
func (m1 Mat2x4) Transpose() Mat4x2 { _ = "STUB: not implemented"; return *new(Mat4x2) }

// ApproxEqual performs an element-wise approximate equality test between two matrices,
// as if FloatEqual had been used.
func (m1 Mat2x4) ApproxEqual(m2 Mat2x4) bool { _ = "STUB: not implemented"; return false }

// ApproxEqualThreshold performs an element-wise approximate equality test between two matrices
// with a given epsilon threshold, as if FloatEqualThreshold had been used.
func (m1 Mat2x4) ApproxEqualThreshold(m2 Mat2x4, threshold float64) bool {
	_ = "STUB: not implemented"
	return false
}

// ApproxFuncEqual performs an element-wise approximate equality test between two matrices
// with a given equality functions, intended to be used with FloatEqualFunc; although and comparison
// function may be used in practice.
func (m1 Mat2x4) ApproxFuncEqual(m2 Mat2x4, eq func(float64, float64) bool) bool {
	_ = "STUB: not implemented"
	return false
}

// NumRows returns the number of rows in this matrix
func (m Mat2x4) NumRows() int {
	_ = "STUB: not implemented"

	// NumCols returns the number of columns in this matrix
	return 0
}

func (m Mat2x4) NumCols() int {
	_ = "STUB: not implemented"

	// At returns the matrix element at the given row and column.
	// This is equivalent to mat[col * numRow + row] where numRow is constant
	// (E.G. for a Mat3x2 it's equal to 3)
	//
	// This method is garbage-in garbage-out. For instance, on a Mat4 asking for
	// At(5,0) will work just like At(1,1). Or it may panic if it's out of bounds.
	return 0
}

func (m Mat2x4) At(row, col int) float64 { _ = "STUB: not implemented"; return 0 }

// Set sets the corresponding matrix element at the given row and column.
// This has a pointer receiver because it mutates the matrix.
//
// This method is garbage-in garbage-out. For instance, on a Mat4 asking for
// Set(5,0,val) will work just like Set(1,1,val). Or it may panic if it's out of bounds.
func (m *Mat2x4) Set(row, col int, value float64) { _ = "STUB: not implemented"; return }

// Index returns the index of the given row and column, to be used with direct
// access. E.G. Index(0,0) = 0.
//
// This is a garbage-in garbage-out method. For instance, on a Mat4 asking for the index of
// (5,0) will work the same as asking for (1,1). Or it may give you a value that will cause
// a panic if you try to access the array with it if it's truly out of bounds.
func (m Mat2x4) Index(row, col int) int {
	_ = "STUB: not implemented"

	// Row returns a vector representing the corresponding row (starting at row 0).
	// This package makes no distinction between row and column vectors, so it
	// will be a normal VecM for a MxN matrix.
	return 0
}

func (m Mat2x4) Row(row int) Vec4 { _ = "STUB: not implemented"; return *new(Vec4) }

// Rows decomposes a matrix into its corresponding row vectors.
// This is equivalent to calling mat.Row for each row.
func (m Mat2x4) Rows() (row0, row1 Vec4) {
	_ = "STUB: not implemented"
	return *

	// Col returns a vector representing the corresponding column (starting at col 0).
	// This package makes no distinction between row and column vectors, so it
	// will be a normal VecN for a MxN matrix.
	new(Vec4), *new(Vec4)
}

func (m Mat2x4) Col(col int) Vec2 { _ = "STUB: not implemented"; return *new(Vec2) }

// Cols decomposes a matrix into its corresponding column vectors.
// This is equivalent to calling mat.Col for each column.
func (m Mat2x4) Cols() (col0, col1, col2, col3 Vec2) {
	_ = "STUB: not implemented"
	return *new(Vec2), *new(Vec2), *new(Vec2), *new(Vec2)
}

// Abs returns the element-wise absolute value of this matrix
func (m Mat2x4) Abs() Mat2x4 { _ = "STUB: not implemented"; return *new(Mat2x4) }

// Pretty prints the matrix
func (m Mat2x4) String() string { _ = "STUB: not implemented"; return "" }

// SetCol sets a Column within the Matrix, so it mutates the calling matrix.
func (m *Mat3x2) SetCol(col int, v Vec3) { _ = "STUB: not implemented"; return }

// SetRow sets a Row within the Matrix, so it mutates the calling matrix.
func (m *Mat3x2) SetRow(row int, v Vec2) { _ = "STUB: not implemented"; return }

// Mat3x2FromRows builds a new matrix from row vectors.
// The resulting matrix will still be in column major order, but this can be
// good for hand-building matrices.

func Mat3x2FromRows(row0, row1, row2 Vec2) Mat3x2 { _ = "STUB: not implemented"; return *new(Mat3x2) }

// Mat3x2FromCols builds a new matrix from column vectors.
func Mat3x2FromCols(col0, col1 Vec3) Mat3x2 { _ = "STUB: not implemented"; return *new(Mat3x2) }

// Add performs an element-wise addition of two matrices, this is
// equivalent to iterating over every element of m1 and adding the corresponding value of m2.
func (m1 Mat3x2) Add(m2 Mat3x2) Mat3x2 { _ = "STUB: not implemented"; return *new(Mat3x2) }

// Sub performs an element-wise subtraction of two matrices, this is
// equivalent to iterating over every element of m1 and subtracting the corresponding value of m2.
func (m1 Mat3x2) Sub(m2 Mat3x2) Mat3x2 { _ = "STUB: not implemented"; return *new(Mat3x2) }

// Mul performs a scalar multiplcation of the matrix. This is equivalent to iterating
// over every element of the matrix and multiply it by c.
func (m1 Mat3x2) Mul(c float64) Mat3x2 { _ = "STUB: not implemented"; return *new(Mat3x2) }

// Mul2x1 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat3x2) Mul2x1(m2 Vec2) Vec3 { _ = "STUB: not implemented"; return *new(Vec3) }

// Mul2 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat3x2) Mul2(m2 Mat2) Mat3x2 { _ = "STUB: not implemented"; return *new(Mat3x2) }

// Mul2x3 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat3x2) Mul2x3(m2 Mat2x3) Mat3 { _ = "STUB: not implemented"; return *new(Mat3) }

// Mul2x4 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat3x2) Mul2x4(m2 Mat2x4) Mat3x4 { _ = "STUB: not implemented"; return *new(Mat3x4) }

// Transpose produces the transpose of this matrix. For any MxN matrix
// the transpose is an NxM matrix with the rows swapped with the columns. For instance
// the transpose of the Mat3x2 is a Mat2x3 like so:
//
//	[[a b]]    [[a c e]]
//	[[c d]] =  [[b d f]]
//	[[e f]]
func (m1 Mat3x2) Transpose() Mat2x3 { _ = "STUB: not implemented"; return *new(Mat2x3) }

// ApproxEqual performs an element-wise approximate equality test between two matrices,
// as if FloatEqual had been used.
func (m1 Mat3x2) ApproxEqual(m2 Mat3x2) bool { _ = "STUB: not implemented"; return false }

// ApproxEqualThreshold performs an element-wise approximate equality test between two matrices
// with a given epsilon threshold, as if FloatEqualThreshold had been used.
func (m1 Mat3x2) ApproxEqualThreshold(m2 Mat3x2, threshold float64) bool {
	_ = "STUB: not implemented"
	return false
}

// ApproxFuncEqual performs an element-wise approximate equality test between two matrices
// with a given equality functions, intended to be used with FloatEqualFunc; although and comparison
// function may be used in practice.
func (m1 Mat3x2) ApproxFuncEqual(m2 Mat3x2, eq func(float64, float64) bool) bool {
	_ = "STUB: not implemented"
	return false
}

// NumRows returns the number of rows in this matrix
func (m Mat3x2) NumRows() int {
	_ = "STUB: not implemented"

	// NumCols returns the number of columns in this matrix
	return 0
}

func (m Mat3x2) NumCols() int {
	_ = "STUB: not implemented"

	// At returns the matrix element at the given row and column.
	// This is equivalent to mat[col * numRow + row] where numRow is constant
	// (E.G. for a Mat3x2 it's equal to 3)
	//
	// This method is garbage-in garbage-out. For instance, on a Mat4 asking for
	// At(5,0) will work just like At(1,1). Or it may panic if it's out of bounds.
	return 0
}

func (m Mat3x2) At(row, col int) float64 { _ = "STUB: not implemented"; return 0 }

// Set sets the corresponding matrix element at the given row and column.
// This has a pointer receiver because it mutates the matrix.
//
// This method is garbage-in garbage-out. For instance, on a Mat4 asking for
// Set(5,0,val) will work just like Set(1,1,val). Or it may panic if it's out of bounds.
func (m *Mat3x2) Set(row, col int, value float64) { _ = "STUB: not implemented"; return }

// Index returns the index of the given row and column, to be used with direct
// access. E.G. Index(0,0) = 0.
//
// This is a garbage-in garbage-out method. For instance, on a Mat4 asking for the index of
// (5,0) will work the same as asking for (1,1). Or it may give you a value that will cause
// a panic if you try to access the array with it if it's truly out of bounds.
func (m Mat3x2) Index(row, col int) int {
	_ = "STUB: not implemented"

	// Row returns a vector representing the corresponding row (starting at row 0).
	// This package makes no distinction between row and column vectors, so it
	// will be a normal VecM for a MxN matrix.
	return 0
}

func (m Mat3x2) Row(row int) Vec2 { _ = "STUB: not implemented"; return *new(Vec2) }

// Rows decomposes a matrix into its corresponding row vectors.
// This is equivalent to calling mat.Row for each row.
func (m Mat3x2) Rows() (row0, row1, row2 Vec2) {
	_ = "STUB: not implemented"
	return *new(Vec2), *new(Vec2), *new(Vec2)
}

// Col returns a vector representing the corresponding column (starting at col 0).
// This package makes no distinction between row and column vectors, so it
// will be a normal VecN for a MxN matrix.
func (m Mat3x2) Col(col int) Vec3 { _ = "STUB: not implemented"; return *new(Vec3) }

// Cols decomposes a matrix into its corresponding column vectors.
// This is equivalent to calling mat.Col for each column.
func (m Mat3x2) Cols() (col0, col1 Vec3) {
	_ = "STUB: not implemented"
	return *

	// Abs returns the element-wise absolute value of this matrix
	new(Vec3), *new(Vec3)
}

func (m Mat3x2) Abs() Mat3x2 { _ = "STUB: not implemented"; return *new(Mat3x2) }

// Pretty prints the matrix
func (m Mat3x2) String() string { _ = "STUB: not implemented"; return "" }

// SetCol sets a Column within the Matrix, so it mutates the calling matrix.
func (m *Mat3) SetCol(col int, v Vec3) { _ = "STUB: not implemented"; return }

// SetRow sets a Row within the Matrix, so it mutates the calling matrix.
func (m *Mat3) SetRow(row int, v Vec3) { _ = "STUB: not implemented"; return }

// Diag is a basic operation on a square matrix that simply
// returns main diagonal (meaning all elements such that row==col).
func (m Mat3) Diag() Vec3 { _ = "STUB: not implemented"; return *new(Vec3) }

// Ident3 returns the 3x3 identity matrix.
// The identity matrix is a square matrix with the value 1 on its
// diagonals. The characteristic property of the identity matrix is that
// any matrix multiplied by it is itself. (MI = M; IN = N)
func Ident3() Mat3 { _ = "STUB: not implemented"; return *new(Mat3) }

// Diag3 creates a diagonal matrix from the entries of the input vector.
// That is, for each pointer for row==col, vector[row] is the entry. Otherwise it's 0.
//
// Another way to think about it is that the identity is this function where the every vector element is 1.
func Diag3(v Vec3) Mat3 { _ = "STUB: not implemented"; return *new(Mat3) }

// Mat3FromRows builds a new matrix from row vectors.
// The resulting matrix will still be in column major order, but this can be
// good for hand-building matrices.

func Mat3FromRows(row0, row1, row2 Vec3) Mat3 { _ = "STUB: not implemented"; return *new(Mat3) }

// Mat3FromCols builds a new matrix from column vectors.
func Mat3FromCols(col0, col1, col2 Vec3) Mat3 { _ = "STUB: not implemented"; return *new(Mat3) }

// Add performs an element-wise addition of two matrices, this is
// equivalent to iterating over every element of m1 and adding the corresponding value of m2.
func (m1 Mat3) Add(m2 Mat3) Mat3 { _ = "STUB: not implemented"; return *new(Mat3) }

// Sub performs an element-wise subtraction of two matrices, this is
// equivalent to iterating over every element of m1 and subtracting the corresponding value of m2.
func (m1 Mat3) Sub(m2 Mat3) Mat3 { _ = "STUB: not implemented"; return *new(Mat3) }

// Mul performs a scalar multiplcation of the matrix. This is equivalent to iterating
// over every element of the matrix and multiply it by c.
func (m1 Mat3) Mul(c float64) Mat3 { _ = "STUB: not implemented"; return *new(Mat3) }

// Mul3x1 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat3) Mul3x1(m2 Vec3) Vec3 { _ = "STUB: not implemented"; return *new(Vec3) }

// Mul3x2 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat3) Mul3x2(m2 Mat3x2) Mat3x2 { _ = "STUB: not implemented"; return *new(Mat3x2) }

// Mul3 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat3) Mul3(m2 Mat3) Mat3 { _ = "STUB: not implemented"; return *new(Mat3) }

// Mul3x4 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat3) Mul3x4(m2 Mat3x4) Mat3x4 { _ = "STUB: not implemented"; return *new(Mat3x4) }

// Transpose produces the transpose of this matrix. For any MxN matrix
// the transpose is an NxM matrix with the rows swapped with the columns. For instance
// the transpose of the Mat3x2 is a Mat2x3 like so:
//
//	[[a b]]    [[a c e]]
//	[[c d]] =  [[b d f]]
//	[[e f]]
func (m1 Mat3) Transpose() Mat3 { _ = "STUB: not implemented"; return *new(Mat3) }

// Det returns the determinant of a matrix. It is a measure of a square matrix's
// singularity and invertability, among other things. In this library, the
// determinant is hard coded based on pre-computed cofactor expansion, and uses
// no loops. Of course, the addition and multiplication must still be done.
func (m Mat3) Det() float64 { _ = "STUB: not implemented"; return 0 }

// Inv computes the inverse of a square matrix. An inverse is a square matrix such that when multiplied by the
// original, yields the identity.
//
// M_inv * M = M * M_inv = I
//
// In this library, the math is precomputed, and uses no loops, though the multiplications, additions, determinant calculation, and scaling
// are still done. This can still be (relatively) expensive for a 4x4.
//
// This function checks the determinant to see if the matrix is invertible.
// If the determinant is 0.0, this function returns the zero matrix. However, due to floating point errors, it is
// entirely plausible to get a false positive or negative.
// In the future, an alternate function may be written which takes in a pre-computed determinant.
func (m Mat3) Inv() Mat3 { _ = "STUB: not implemented"; return *new(Mat3) }

// ApproxEqual performs an element-wise approximate equality test between two matrices,
// as if FloatEqual had been used.
func (m1 Mat3) ApproxEqual(m2 Mat3) bool { _ = "STUB: not implemented"; return false }

// ApproxEqualThreshold performs an element-wise approximate equality test between two matrices
// with a given epsilon threshold, as if FloatEqualThreshold had been used.
func (m1 Mat3) ApproxEqualThreshold(m2 Mat3, threshold float64) bool {
	_ = "STUB: not implemented"
	return false
}

// ApproxFuncEqual performs an element-wise approximate equality test between two matrices
// with a given equality functions, intended to be used with FloatEqualFunc; although and comparison
// function may be used in practice.
func (m1 Mat3) ApproxFuncEqual(m2 Mat3, eq func(float64, float64) bool) bool {
	_ = "STUB: not implemented"
	return false
}

// NumRows returns the number of rows in this matrix
func (m Mat3) NumRows() int {
	_ = "STUB: not implemented"

	// NumCols returns the number of columns in this matrix
	return 0
}

func (m Mat3) NumCols() int {
	_ = "STUB: not implemented"

	// At returns the matrix element at the given row and column.
	// This is equivalent to mat[col * numRow + row] where numRow is constant
	// (E.G. for a Mat3x2 it's equal to 3)
	//
	// This method is garbage-in garbage-out. For instance, on a Mat4 asking for
	// At(5,0) will work just like At(1,1). Or it may panic if it's out of bounds.
	return 0
}

func (m Mat3) At(row, col int) float64 { _ = "STUB: not implemented"; return 0 }

// Set sets the corresponding matrix element at the given row and column.
// This has a pointer receiver because it mutates the matrix.
//
// This method is garbage-in garbage-out. For instance, on a Mat4 asking for
// Set(5,0,val) will work just like Set(1,1,val). Or it may panic if it's out of bounds.
func (m *Mat3) Set(row, col int, value float64) { _ = "STUB: not implemented"; return }

// Index returns the index of the given row and column, to be used with direct
// access. E.G. Index(0,0) = 0.
//
// This is a garbage-in garbage-out method. For instance, on a Mat4 asking for the index of
// (5,0) will work the same as asking for (1,1). Or it may give you a value that will cause
// a panic if you try to access the array with it if it's truly out of bounds.
func (m Mat3) Index(row, col int) int {
	_ = "STUB: not implemented"

	// Row returns a vector representing the corresponding row (starting at row 0).
	// This package makes no distinction between row and column vectors, so it
	// will be a normal VecM for a MxN matrix.
	return 0
}

func (m Mat3) Row(row int) Vec3 { _ = "STUB: not implemented"; return *new(Vec3) }

// Rows decomposes a matrix into its corresponding row vectors.
// This is equivalent to calling mat.Row for each row.
func (m Mat3) Rows() (row0, row1, row2 Vec3) {
	_ = "STUB: not implemented"
	return *new(Vec3), *new(Vec3), *new(Vec3)
}

// Col returns a vector representing the corresponding column (starting at col 0).
// This package makes no distinction between row and column vectors, so it
// will be a normal VecN for a MxN matrix.
func (m Mat3) Col(col int) Vec3 { _ = "STUB: not implemented"; return *new(Vec3) }

// Cols decomposes a matrix into its corresponding column vectors.
// This is equivalent to calling mat.Col for each column.
func (m Mat3) Cols() (col0, col1, col2 Vec3) {
	_ = "STUB: not implemented"
	return *new(Vec3), *new(Vec3), *new(Vec3)
}

// Trace is a basic operation on a square matrix that simply
// sums up all elements on the main diagonal (meaning all elements such that row==col).
func (m Mat3) Trace() float64 { _ = "STUB: not implemented"; return 0 }

// Abs returns the element-wise absolute value of this matrix
func (m Mat3) Abs() Mat3 { _ = "STUB: not implemented"; return *new(Mat3) }

// Pretty prints the matrix
func (m Mat3) String() string { _ = "STUB: not implemented"; return "" }

// SetCol sets a Column within the Matrix, so it mutates the calling matrix.
func (m *Mat3x4) SetCol(col int, v Vec3) { _ = "STUB: not implemented"; return }

// SetRow sets a Row within the Matrix, so it mutates the calling matrix.
func (m *Mat3x4) SetRow(row int, v Vec4) { _ = "STUB: not implemented"; return }

// Mat3x4FromRows builds a new matrix from row vectors.
// The resulting matrix will still be in column major order, but this can be
// good for hand-building matrices.

func Mat3x4FromRows(row0, row1, row2 Vec4) Mat3x4 { _ = "STUB: not implemented"; return *new(Mat3x4) }

// Mat3x4FromCols builds a new matrix from column vectors.
func Mat3x4FromCols(col0, col1, col2, col3 Vec3) Mat3x4 {
	_ = "STUB: not implemented"
	return *new(Mat3x4)
}

// Add performs an element-wise addition of two matrices, this is
// equivalent to iterating over every element of m1 and adding the corresponding value of m2.
func (m1 Mat3x4) Add(m2 Mat3x4) Mat3x4 { _ = "STUB: not implemented"; return *new(Mat3x4) }

// Sub performs an element-wise subtraction of two matrices, this is
// equivalent to iterating over every element of m1 and subtracting the corresponding value of m2.
func (m1 Mat3x4) Sub(m2 Mat3x4) Mat3x4 { _ = "STUB: not implemented"; return *new(Mat3x4) }

// Mul performs a scalar multiplcation of the matrix. This is equivalent to iterating
// over every element of the matrix and multiply it by c.
func (m1 Mat3x4) Mul(c float64) Mat3x4 { _ = "STUB: not implemented"; return *new(Mat3x4) }

// Mul4x1 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat3x4) Mul4x1(m2 Vec4) Vec3 { _ = "STUB: not implemented"; return *new(Vec3) }

// Mul4x2 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat3x4) Mul4x2(m2 Mat4x2) Mat3x2 { _ = "STUB: not implemented"; return *new(Mat3x2) }

// Mul4x3 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat3x4) Mul4x3(m2 Mat4x3) Mat3 { _ = "STUB: not implemented"; return *new(Mat3) }

// Mul4 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat3x4) Mul4(m2 Mat4) Mat3x4 { _ = "STUB: not implemented"; return *new(Mat3x4) }

// Transpose produces the transpose of this matrix. For any MxN matrix
// the transpose is an NxM matrix with the rows swapped with the columns. For instance
// the transpose of the Mat3x2 is a Mat2x3 like so:
//
//	[[a b]]    [[a c e]]
//	[[c d]] =  [[b d f]]
//	[[e f]]
func (m1 Mat3x4) Transpose() Mat4x3 { _ = "STUB: not implemented"; return *new(Mat4x3) }

// ApproxEqual performs an element-wise approximate equality test between two matrices,
// as if FloatEqual had been used.
func (m1 Mat3x4) ApproxEqual(m2 Mat3x4) bool { _ = "STUB: not implemented"; return false }

// ApproxEqualThreshold performs an element-wise approximate equality test between two matrices
// with a given epsilon threshold, as if FloatEqualThreshold had been used.
func (m1 Mat3x4) ApproxEqualThreshold(m2 Mat3x4, threshold float64) bool {
	_ = "STUB: not implemented"
	return false
}

// ApproxFuncEqual performs an element-wise approximate equality test between two matrices
// with a given equality functions, intended to be used with FloatEqualFunc; although and comparison
// function may be used in practice.
func (m1 Mat3x4) ApproxFuncEqual(m2 Mat3x4, eq func(float64, float64) bool) bool {
	_ = "STUB: not implemented"
	return false
}

// NumRows returns the number of rows in this matrix
func (m Mat3x4) NumRows() int {
	_ = "STUB: not implemented"

	// NumCols returns the number of columns in this matrix
	return 0
}

func (m Mat3x4) NumCols() int {
	_ = "STUB: not implemented"

	// At returns the matrix element at the given row and column.
	// This is equivalent to mat[col * numRow + row] where numRow is constant
	// (E.G. for a Mat3x2 it's equal to 3)
	//
	// This method is garbage-in garbage-out. For instance, on a Mat4 asking for
	// At(5,0) will work just like At(1,1). Or it may panic if it's out of bounds.
	return 0
}

func (m Mat3x4) At(row, col int) float64 { _ = "STUB: not implemented"; return 0 }

// Set sets the corresponding matrix element at the given row and column.
// This has a pointer receiver because it mutates the matrix.
//
// This method is garbage-in garbage-out. For instance, on a Mat4 asking for
// Set(5,0,val) will work just like Set(1,1,val). Or it may panic if it's out of bounds.
func (m *Mat3x4) Set(row, col int, value float64) { _ = "STUB: not implemented"; return }

// Index returns the index of the given row and column, to be used with direct
// access. E.G. Index(0,0) = 0.
//
// This is a garbage-in garbage-out method. For instance, on a Mat4 asking for the index of
// (5,0) will work the same as asking for (1,1). Or it may give you a value that will cause
// a panic if you try to access the array with it if it's truly out of bounds.
func (m Mat3x4) Index(row, col int) int {
	_ = "STUB: not implemented"

	// Row returns a vector representing the corresponding row (starting at row 0).
	// This package makes no distinction between row and column vectors, so it
	// will be a normal VecM for a MxN matrix.
	return 0
}

func (m Mat3x4) Row(row int) Vec4 { _ = "STUB: not implemented"; return *new(Vec4) }

// Rows decomposes a matrix into its corresponding row vectors.
// This is equivalent to calling mat.Row for each row.
func (m Mat3x4) Rows() (row0, row1, row2 Vec4) {
	_ = "STUB: not implemented"
	return *new(Vec4), *new(Vec4), *new(Vec4)
}

// Col returns a vector representing the corresponding column (starting at col 0).
// This package makes no distinction between row and column vectors, so it
// will be a normal VecN for a MxN matrix.
func (m Mat3x4) Col(col int) Vec3 { _ = "STUB: not implemented"; return *new(Vec3) }

// Cols decomposes a matrix into its corresponding column vectors.
// This is equivalent to calling mat.Col for each column.
func (m Mat3x4) Cols() (col0, col1, col2, col3 Vec3) {
	_ = "STUB: not implemented"
	return *new(Vec3), *new(Vec3), *new(Vec3), *new(Vec3)
}

// Abs returns the element-wise absolute value of this matrix
func (m Mat3x4) Abs() Mat3x4 { _ = "STUB: not implemented"; return *new(Mat3x4) }

// Pretty prints the matrix
func (m Mat3x4) String() string { _ = "STUB: not implemented"; return "" }

// SetCol sets a Column within the Matrix, so it mutates the calling matrix.
func (m *Mat4x2) SetCol(col int, v Vec4) { _ = "STUB: not implemented"; return }

// SetRow sets a Row within the Matrix, so it mutates the calling matrix.
func (m *Mat4x2) SetRow(row int, v Vec2) { _ = "STUB: not implemented"; return }

// Mat4x2FromRows builds a new matrix from row vectors.
// The resulting matrix will still be in column major order, but this can be
// good for hand-building matrices.

func Mat4x2FromRows(row0, row1, row2, row3 Vec2) Mat4x2 {
	_ = "STUB: not implemented"
	return *new(Mat4x2)
}

// Mat4x2FromCols builds a new matrix from column vectors.
func Mat4x2FromCols(col0, col1 Vec4) Mat4x2 { _ = "STUB: not implemented"; return *new(Mat4x2) }

// Add performs an element-wise addition of two matrices, this is
// equivalent to iterating over every element of m1 and adding the corresponding value of m2.
func (m1 Mat4x2) Add(m2 Mat4x2) Mat4x2 { _ = "STUB: not implemented"; return *new(Mat4x2) }

// Sub performs an element-wise subtraction of two matrices, this is
// equivalent to iterating over every element of m1 and subtracting the corresponding value of m2.
func (m1 Mat4x2) Sub(m2 Mat4x2) Mat4x2 { _ = "STUB: not implemented"; return *new(Mat4x2) }

// Mul performs a scalar multiplcation of the matrix. This is equivalent to iterating
// over every element of the matrix and multiply it by c.
func (m1 Mat4x2) Mul(c float64) Mat4x2 { _ = "STUB: not implemented"; return *new(Mat4x2) }

// Mul2x1 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat4x2) Mul2x1(m2 Vec2) Vec4 { _ = "STUB: not implemented"; return *new(Vec4) }

// Mul2 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat4x2) Mul2(m2 Mat2) Mat4x2 { _ = "STUB: not implemented"; return *new(Mat4x2) }

// Mul2x3 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat4x2) Mul2x3(m2 Mat2x3) Mat4x3 { _ = "STUB: not implemented"; return *new(Mat4x3) }

// Mul2x4 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat4x2) Mul2x4(m2 Mat2x4) Mat4 { _ = "STUB: not implemented"; return *new(Mat4) }

// Transpose produces the transpose of this matrix. For any MxN matrix
// the transpose is an NxM matrix with the rows swapped with the columns. For instance
// the transpose of the Mat3x2 is a Mat2x3 like so:
//
//	[[a b]]    [[a c e]]
//	[[c d]] =  [[b d f]]
//	[[e f]]
func (m1 Mat4x2) Transpose() Mat2x4 { _ = "STUB: not implemented"; return *new(Mat2x4) }

// ApproxEqual performs an element-wise approximate equality test between two matrices,
// as if FloatEqual had been used.
func (m1 Mat4x2) ApproxEqual(m2 Mat4x2) bool { _ = "STUB: not implemented"; return false }

// ApproxEqualThreshold performs an element-wise approximate equality test between two matrices
// with a given epsilon threshold, as if FloatEqualThreshold had been used.
func (m1 Mat4x2) ApproxEqualThreshold(m2 Mat4x2, threshold float64) bool {
	_ = "STUB: not implemented"
	return false
}

// ApproxFuncEqual performs an element-wise approximate equality test between two matrices
// with a given equality functions, intended to be used with FloatEqualFunc; although and comparison
// function may be used in practice.
func (m1 Mat4x2) ApproxFuncEqual(m2 Mat4x2, eq func(float64, float64) bool) bool {
	_ = "STUB: not implemented"
	return false
}

// NumRows returns the number of rows in this matrix
func (m Mat4x2) NumRows() int {
	_ = "STUB: not implemented"

	// NumCols returns the number of columns in this matrix
	return 0
}

func (m Mat4x2) NumCols() int {
	_ = "STUB: not implemented"

	// At returns the matrix element at the given row and column.
	// This is equivalent to mat[col * numRow + row] where numRow is constant
	// (E.G. for a Mat3x2 it's equal to 3)
	//
	// This method is garbage-in garbage-out. For instance, on a Mat4 asking for
	// At(5,0) will work just like At(1,1). Or it may panic if it's out of bounds.
	return 0
}

func (m Mat4x2) At(row, col int) float64 { _ = "STUB: not implemented"; return 0 }

// Set sets the corresponding matrix element at the given row and column.
// This has a pointer receiver because it mutates the matrix.
//
// This method is garbage-in garbage-out. For instance, on a Mat4 asking for
// Set(5,0,val) will work just like Set(1,1,val). Or it may panic if it's out of bounds.
func (m *Mat4x2) Set(row, col int, value float64) { _ = "STUB: not implemented"; return }

// Index returns the index of the given row and column, to be used with direct
// access. E.G. Index(0,0) = 0.
//
// This is a garbage-in garbage-out method. For instance, on a Mat4 asking for the index of
// (5,0) will work the same as asking for (1,1). Or it may give you a value that will cause
// a panic if you try to access the array with it if it's truly out of bounds.
func (m Mat4x2) Index(row, col int) int {
	_ = "STUB: not implemented"

	// Row returns a vector representing the corresponding row (starting at row 0).
	// This package makes no distinction between row and column vectors, so it
	// will be a normal VecM for a MxN matrix.
	return 0
}

func (m Mat4x2) Row(row int) Vec2 { _ = "STUB: not implemented"; return *new(Vec2) }

// Rows decomposes a matrix into its corresponding row vectors.
// This is equivalent to calling mat.Row for each row.
func (m Mat4x2) Rows() (row0, row1, row2, row3 Vec2) {
	_ = "STUB: not implemented"
	return *new(Vec2), *new(Vec2), *new(Vec2), *new(Vec2)
}

// Col returns a vector representing the corresponding column (starting at col 0).
// This package makes no distinction between row and column vectors, so it
// will be a normal VecN for a MxN matrix.
func (m Mat4x2) Col(col int) Vec4 { _ = "STUB: not implemented"; return *new(Vec4) }

// Cols decomposes a matrix into its corresponding column vectors.
// This is equivalent to calling mat.Col for each column.
func (m Mat4x2) Cols() (col0, col1 Vec4) {
	_ = "STUB: not implemented"
	return *

	// Abs returns the element-wise absolute value of this matrix
	new(Vec4), *new(Vec4)
}

func (m Mat4x2) Abs() Mat4x2 { _ = "STUB: not implemented"; return *new(Mat4x2) }

// Pretty prints the matrix
func (m Mat4x2) String() string { _ = "STUB: not implemented"; return "" }

// SetCol sets a Column within the Matrix, so it mutates the calling matrix.
func (m *Mat4x3) SetCol(col int, v Vec4) { _ = "STUB: not implemented"; return }

// SetRow sets a Row within the Matrix, so it mutates the calling matrix.
func (m *Mat4x3) SetRow(row int, v Vec3) { _ = "STUB: not implemented"; return }

// Mat4x3FromRows builds a new matrix from row vectors.
// The resulting matrix will still be in column major order, but this can be
// good for hand-building matrices.

func Mat4x3FromRows(row0, row1, row2, row3 Vec3) Mat4x3 {
	_ = "STUB: not implemented"
	return *new(Mat4x3)
}

// Mat4x3FromCols builds a new matrix from column vectors.
func Mat4x3FromCols(col0, col1, col2 Vec4) Mat4x3 { _ = "STUB: not implemented"; return *new(Mat4x3) }

// Add performs an element-wise addition of two matrices, this is
// equivalent to iterating over every element of m1 and adding the corresponding value of m2.
func (m1 Mat4x3) Add(m2 Mat4x3) Mat4x3 { _ = "STUB: not implemented"; return *new(Mat4x3) }

// Sub performs an element-wise subtraction of two matrices, this is
// equivalent to iterating over every element of m1 and subtracting the corresponding value of m2.
func (m1 Mat4x3) Sub(m2 Mat4x3) Mat4x3 { _ = "STUB: not implemented"; return *new(Mat4x3) }

// Mul performs a scalar multiplcation of the matrix. This is equivalent to iterating
// over every element of the matrix and multiply it by c.
func (m1 Mat4x3) Mul(c float64) Mat4x3 { _ = "STUB: not implemented"; return *new(Mat4x3) }

// Mul3x1 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat4x3) Mul3x1(m2 Vec3) Vec4 { _ = "STUB: not implemented"; return *new(Vec4) }

// Mul3x2 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat4x3) Mul3x2(m2 Mat3x2) Mat4x2 { _ = "STUB: not implemented"; return *new(Mat4x2) }

// Mul3 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat4x3) Mul3(m2 Mat3) Mat4x3 { _ = "STUB: not implemented"; return *new(Mat4x3) }

// Mul3x4 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat4x3) Mul3x4(m2 Mat3x4) Mat4 { _ = "STUB: not implemented"; return *new(Mat4) }

// Transpose produces the transpose of this matrix. For any MxN matrix
// the transpose is an NxM matrix with the rows swapped with the columns. For instance
// the transpose of the Mat3x2 is a Mat2x3 like so:
//
//	[[a b]]    [[a c e]]
//	[[c d]] =  [[b d f]]
//	[[e f]]
func (m1 Mat4x3) Transpose() Mat3x4 { _ = "STUB: not implemented"; return *new(Mat3x4) }

// ApproxEqual performs an element-wise approximate equality test between two matrices,
// as if FloatEqual had been used.
func (m1 Mat4x3) ApproxEqual(m2 Mat4x3) bool { _ = "STUB: not implemented"; return false }

// ApproxEqualThreshold performs an element-wise approximate equality test between two matrices
// with a given epsilon threshold, as if FloatEqualThreshold had been used.
func (m1 Mat4x3) ApproxEqualThreshold(m2 Mat4x3, threshold float64) bool {
	_ = "STUB: not implemented"
	return false
}

// ApproxFuncEqual performs an element-wise approximate equality test between two matrices
// with a given equality functions, intended to be used with FloatEqualFunc; although and comparison
// function may be used in practice.
func (m1 Mat4x3) ApproxFuncEqual(m2 Mat4x3, eq func(float64, float64) bool) bool {
	_ = "STUB: not implemented"
	return false
}

// NumRows returns the number of rows in this matrix
func (m Mat4x3) NumRows() int {
	_ = "STUB: not implemented"

	// NumCols returns the number of columns in this matrix
	return 0
}

func (m Mat4x3) NumCols() int {
	_ = "STUB: not implemented"

	// At returns the matrix element at the given row and column.
	// This is equivalent to mat[col * numRow + row] where numRow is constant
	// (E.G. for a Mat3x2 it's equal to 3)
	//
	// This method is garbage-in garbage-out. For instance, on a Mat4 asking for
	// At(5,0) will work just like At(1,1). Or it may panic if it's out of bounds.
	return 0
}

func (m Mat4x3) At(row, col int) float64 { _ = "STUB: not implemented"; return 0 }

// Set sets the corresponding matrix element at the given row and column.
// This has a pointer receiver because it mutates the matrix.
//
// This method is garbage-in garbage-out. For instance, on a Mat4 asking for
// Set(5,0,val) will work just like Set(1,1,val). Or it may panic if it's out of bounds.
func (m *Mat4x3) Set(row, col int, value float64) { _ = "STUB: not implemented"; return }

// Index returns the index of the given row and column, to be used with direct
// access. E.G. Index(0,0) = 0.
//
// This is a garbage-in garbage-out method. For instance, on a Mat4 asking for the index of
// (5,0) will work the same as asking for (1,1). Or it may give you a value that will cause
// a panic if you try to access the array with it if it's truly out of bounds.
func (m Mat4x3) Index(row, col int) int {
	_ = "STUB: not implemented"

	// Row returns a vector representing the corresponding row (starting at row 0).
	// This package makes no distinction between row and column vectors, so it
	// will be a normal VecM for a MxN matrix.
	return 0
}

func (m Mat4x3) Row(row int) Vec3 { _ = "STUB: not implemented"; return *new(Vec3) }

// Rows decomposes a matrix into its corresponding row vectors.
// This is equivalent to calling mat.Row for each row.
func (m Mat4x3) Rows() (row0, row1, row2, row3 Vec3) {
	_ = "STUB: not implemented"
	return *new(Vec3), *new(Vec3), *new(Vec3), *new(Vec3)
}

// Col returns a vector representing the corresponding column (starting at col 0).
// This package makes no distinction between row and column vectors, so it
// will be a normal VecN for a MxN matrix.
func (m Mat4x3) Col(col int) Vec4 { _ = "STUB: not implemented"; return *new(Vec4) }

// Cols decomposes a matrix into its corresponding column vectors.
// This is equivalent to calling mat.Col for each column.
func (m Mat4x3) Cols() (col0, col1, col2 Vec4) {
	_ = "STUB: not implemented"
	return *new(Vec4), *new(Vec4), *new(Vec4)
}

// Abs returns the element-wise absolute value of this matrix
func (m Mat4x3) Abs() Mat4x3 { _ = "STUB: not implemented"; return *new(Mat4x3) }

// Pretty prints the matrix
func (m Mat4x3) String() string { _ = "STUB: not implemented"; return "" }

// SetCol sets a Column within the Matrix, so it mutates the calling matrix.
func (m *Mat4) SetCol(col int, v Vec4) { _ = "STUB: not implemented"; return }

// SetRow sets a Row within the Matrix, so it mutates the calling matrix.
func (m *Mat4) SetRow(row int, v Vec4) { _ = "STUB: not implemented"; return }

// Diag is a basic operation on a square matrix that simply
// returns main diagonal (meaning all elements such that row==col).
func (m Mat4) Diag() Vec4 { _ = "STUB: not implemented"; return *new(Vec4) }

// Ident4 returns the 4x4 identity matrix.
// The identity matrix is a square matrix with the value 1 on its
// diagonals. The characteristic property of the identity matrix is that
// any matrix multiplied by it is itself. (MI = M; IN = N)
func Ident4() Mat4 { _ = "STUB: not implemented"; return *new(Mat4) }

// Diag4 creates a diagonal matrix from the entries of the input vector.
// That is, for each pointer for row==col, vector[row] is the entry. Otherwise it's 0.
//
// Another way to think about it is that the identity is this function where the every vector element is 1.
func Diag4(v Vec4) Mat4 { _ = "STUB: not implemented"; return *new(Mat4) }

// Mat4FromRows builds a new matrix from row vectors.
// The resulting matrix will still be in column major order, but this can be
// good for hand-building matrices.

func Mat4FromRows(row0, row1, row2, row3 Vec4) Mat4 { _ = "STUB: not implemented"; return *new(Mat4) }

// Mat4FromCols builds a new matrix from column vectors.
func Mat4FromCols(col0, col1, col2, col3 Vec4) Mat4 { _ = "STUB: not implemented"; return *new(Mat4) }

// Add performs an element-wise addition of two matrices, this is
// equivalent to iterating over every element of m1 and adding the corresponding value of m2.
func (m1 Mat4) Add(m2 Mat4) Mat4 { _ = "STUB: not implemented"; return *new(Mat4) }

// Sub performs an element-wise subtraction of two matrices, this is
// equivalent to iterating over every element of m1 and subtracting the corresponding value of m2.
func (m1 Mat4) Sub(m2 Mat4) Mat4 { _ = "STUB: not implemented"; return *new(Mat4) }

// Mul performs a scalar multiplcation of the matrix. This is equivalent to iterating
// over every element of the matrix and multiply it by c.
func (m1 Mat4) Mul(c float64) Mat4 { _ = "STUB: not implemented"; return *new(Mat4) }

// Mul4x1 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat4) Mul4x1(m2 Vec4) Vec4 { _ = "STUB: not implemented"; return *new(Vec4) }

// Mul4x2 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat4) Mul4x2(m2 Mat4x2) Mat4x2 { _ = "STUB: not implemented"; return *new(Mat4x2) }

// Mul4x3 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat4) Mul4x3(m2 Mat4x3) Mat4x3 { _ = "STUB: not implemented"; return *new(Mat4x3) }

// Mul4 performs a "matrix product" between this matrix
// and another of the given dimension. For any two matrices of dimensionality
// MxN and NxO, the result will be MxO. For instance, Mat4 multiplied using
// Mul4x2 will result in a Mat4x2.
func (m1 Mat4) Mul4(m2 Mat4) Mat4 { _ = "STUB: not implemented"; return *new(Mat4) }

// Transpose produces the transpose of this matrix. For any MxN matrix
// the transpose is an NxM matrix with the rows swapped with the columns. For instance
// the transpose of the Mat3x2 is a Mat2x3 like so:
//
//	[[a b]]    [[a c e]]
//	[[c d]] =  [[b d f]]
//	[[e f]]
func (m1 Mat4) Transpose() Mat4 { _ = "STUB: not implemented"; return *new(Mat4) }

// Det returns the determinant of a matrix. It is a measure of a square matrix's
// singularity and invertability, among other things. In this library, the
// determinant is hard coded based on pre-computed cofactor expansion, and uses
// no loops. Of course, the addition and multiplication must still be done.
func (m Mat4) Det() float64 { _ = "STUB: not implemented"; return 0 }

// Inv computes the inverse of a square matrix. An inverse is a square matrix such that when multiplied by the
// original, yields the identity.
//
// M_inv * M = M * M_inv = I
//
// In this library, the math is precomputed, and uses no loops, though the multiplications, additions, determinant calculation, and scaling
// are still done. This can still be (relatively) expensive for a 4x4.
//
// This function checks the determinant to see if the matrix is invertible.
// If the determinant is 0.0, this function returns the zero matrix. However, due to floating point errors, it is
// entirely plausible to get a false positive or negative.
// In the future, an alternate function may be written which takes in a pre-computed determinant.
func (m Mat4) Inv() Mat4 { _ = "STUB: not implemented"; return *new(Mat4) }

// ApproxEqual performs an element-wise approximate equality test between two matrices,
// as if FloatEqual had been used.
func (m1 Mat4) ApproxEqual(m2 Mat4) bool { _ = "STUB: not implemented"; return false }

// ApproxEqualThreshold performs an element-wise approximate equality test between two matrices
// with a given epsilon threshold, as if FloatEqualThreshold had been used.
func (m1 Mat4) ApproxEqualThreshold(m2 Mat4, threshold float64) bool {
	_ = "STUB: not implemented"
	return false
}

// ApproxFuncEqual performs an element-wise approximate equality test between two matrices
// with a given equality functions, intended to be used with FloatEqualFunc; although and comparison
// function may be used in practice.
func (m1 Mat4) ApproxFuncEqual(m2 Mat4, eq func(float64, float64) bool) bool {
	_ = "STUB: not implemented"
	return false
}

// NumRows returns the number of rows in this matrix
func (m Mat4) NumRows() int {
	_ = "STUB: not implemented"

	// NumCols returns the number of columns in this matrix
	return 0
}

func (m Mat4) NumCols() int {
	_ = "STUB: not implemented"

	// At returns the matrix element at the given row and column.
	// This is equivalent to mat[col * numRow + row] where numRow is constant
	// (E.G. for a Mat3x2 it's equal to 3)
	//
	// This method is garbage-in garbage-out. For instance, on a Mat4 asking for
	// At(5,0) will work just like At(1,1). Or it may panic if it's out of bounds.
	return 0
}

func (m Mat4) At(row, col int) float64 { _ = "STUB: not implemented"; return 0 }

// Set sets the corresponding matrix element at the given row and column.
// This has a pointer receiver because it mutates the matrix.
//
// This method is garbage-in garbage-out. For instance, on a Mat4 asking for
// Set(5,0,val) will work just like Set(1,1,val). Or it may panic if it's out of bounds.
func (m *Mat4) Set(row, col int, value float64) { _ = "STUB: not implemented"; return }

// Index returns the index of the given row and column, to be used with direct
// access. E.G. Index(0,0) = 0.
//
// This is a garbage-in garbage-out method. For instance, on a Mat4 asking for the index of
// (5,0) will work the same as asking for (1,1). Or it may give you a value that will cause
// a panic if you try to access the array with it if it's truly out of bounds.
func (m Mat4) Index(row, col int) int {
	_ = "STUB: not implemented"

	// Row returns a vector representing the corresponding row (starting at row 0).
	// This package makes no distinction between row and column vectors, so it
	// will be a normal VecM for a MxN matrix.
	return 0
}

func (m Mat4) Row(row int) Vec4 { _ = "STUB: not implemented"; return *new(Vec4) }

// Rows decomposes a matrix into its corresponding row vectors.
// This is equivalent to calling mat.Row for each row.
func (m Mat4) Rows() (row0, row1, row2, row3 Vec4) {
	_ = "STUB: not implemented"
	return *new(Vec4), *new(Vec4), *new(Vec4), *new(Vec4)
}

// Col returns a vector representing the corresponding column (starting at col 0).
// This package makes no distinction between row and column vectors, so it
// will be a normal VecN for a MxN matrix.
func (m Mat4) Col(col int) Vec4 { _ = "STUB: not implemented"; return *new(Vec4) }

// Cols decomposes a matrix into its corresponding column vectors.
// This is equivalent to calling mat.Col for each column.
func (m Mat4) Cols() (col0, col1, col2, col3 Vec4) {
	_ = "STUB: not implemented"
	return *new(Vec4), *new(Vec4), *new(Vec4), *new(Vec4)
}

// Trace is a basic operation on a square matrix that simply
// sums up all elements on the main diagonal (meaning all elements such that row==col).
func (m Mat4) Trace() float64 { _ = "STUB: not implemented"; return 0 }

// Abs returns the element-wise absolute value of this matrix
func (m Mat4) Abs() Mat4 { _ = "STUB: not implemented"; return *new(Mat4) }

// Pretty prints the matrix
func (m Mat4) String() string { _ = "STUB: not implemented"; return "" }
